name: CI/CD Test Pipeline

on:
  push:
    branches:
      - master
      - production

env:
  DOMAIN: ${{ secrets.DOMAIN }}
  TRAEFIK_TAG: ${{ secrets.TRAEFIK_TAG }}
  STACK_NAME: ${{ secrets.STACK_NAME }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pip dependencies
        run: pip install cookiecutter httpcore tenacity h11

      - name: Run tests
        run: sh ./scripts/test.sh
