name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - production

env:
  DOMAIN: ${{ secrets.DOMAIN }}
  TRAEFIK_TAG: ${{ secrets.TRAEFIK_TAG }}
  STACK_NAME: ${{ secrets.STACK_NAME }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-docker-compose@v1

      - name: Run tests
        run: sh ./scripts/test.sh

  